library
drozddmitriy/library pull request #1
Opened 2019-05-23 11:48 UTC by drozddmitriy

2019-06-03 16:46 UTC, dzemlianoi-double commented on Gemfile
> +gem 'faker', '~> 1.9', '>= 1.9.3'
ffaker

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +require './dependency'
let's require in entry file

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +  attr_accessor :masauthor, :masbook, :masorder, :masreader
authors, books, orders, readers

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +  def create_book(title, auth)
separate method `add`

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +  def create_book(title, auth)
author

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +    raise Myvalid, 'wrong argument book or reader!' unless (book.is_a? Book) && (reader.is_a? Reader)
separate methods

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +  def top_reader(quantity = 1)
separate module

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/moduledb.rb
> +    raise Myvalid, 'file not found!' unless File.exist?('data.yml')
1) Myvalid
2) magic strings

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/moduledb.rb
> +    data = YAML.load_file 'data.yml'
data = YAML.load_file 'data.yml' || {}

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/moduledb.rb
> +      @masauthor = data[:masauthor]
data[:masauthor] || []

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/library.rb
> +  def num_of_readers_of_most_popular_books(quantity = 3)
@MaximKoptsov, here!!1

2019-06-03 16:46 UTC, dzemlianoi-double commented on core/moduledb.rb
> +  def save
maybe to_h

2019-06-03 16:46 UTC, dzemlianoi-double commented on entities/author.rb
> +  attr_accessor :name, :biography
attr_accessor?

2019-06-03 16:46 UTC, dzemlianoi-double commented on entities/book.rb
> +    @auth = auth
author?

2019-06-03 16:46 UTC, dzemlianoi-double commented on entities/reader.rb
> +    @house = Integer house
to_i

2019-06-10 11:44 UTC, za4emnik requested changes
1) Fix review comments
2) Check statistics logic
3) Try to create `Statistics` module with statistics and include it to the library
4) Fix rubocop offenses
5) Commit messages should start with a capital letter and more informative. For example `delete module` - bad commit, `Delete module MyModule` - good commit

2019-06-10 11:44 UTC, za4emnik commented on Gemfile
> +gem 'faker', '~> 1.9', '>= 1.9.3'
change to ffaker, please

2019-06-10 11:44 UTC, za4emnik commented on core/modulevalidation.rb
> +module ValidationEntity
use snake_case for a file name

2019-06-10 11:44 UTC, za4emnik commented on core/modulevalidation.rb
> +module ValidationEntity
check and change everywhere

2019-06-10 11:44 UTC, za4emnik commented on core/validation.rb
> +class Validation < StandardError
naming is not clear
try to rename, e.g. DataValidation or smth else

2019-06-10 11:44 UTC, za4emnik commented on main.rb
> +# authors = generator.generate_authors
why comments?

2019-06-10 11:44 UTC, za4emnik commented on core/library.rb
> +    hash.keys.reverse_each.first(quantity)
you simply calculate the sum of readers, bt you need return top readers

2019-06-10 11:44 UTC, za4emnik commented on core/library.rb
> +    hash.keys.reverse_each.first(quantity)
the same

2019-06-26 17:47 UTC, za4emnik requested changes
1) Check name of files
2) Fix rubocop offenses

2019-06-26 17:47 UTC, za4emnik commented on core/module_db.rb
> +module Database
name of file `module_db.rb` does not match the name of module `module Database`

2019-06-26 17:47 UTC, za4emnik commented on core/module_statistic.rb
> +module Statistic
the same

2019-06-26 17:47 UTC, za4emnik commented on core/module_validation.rb
> +module ValidationEntity
check all files, please

2019-06-26 17:47 UTC, za4emnik commented on core/module_statistic.rb
> +    most_books = most_popular_books(orders, quantity)
Why so hard? We can just smth like this: `most_books.to_h.keys.map(&:title)`

2019-08-08 12:31 UTC, za4emnik approved these changes
Merge after fix

2019-08-08 12:31 UTC, za4emnik commented on core/validation.rb
> +class BookValidation < StandardError
remove

2019-08-12 01:41 UTC, merged